name: Build LaTeX

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Generate PDF
      uses: dante-ev/latex-action@latest
      with:
        root_file: luxstat.tex
    - name: Archive generated PDF
      uses: actions/upload-artifact@v2
      with:
        name: luxstat
        path: |
          luxstat.pdf
